apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: affine
type: Opaque
data:
  POSTGRES_USER: dXNlcg==  # base64 encoded "user"
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: affine-config
  namespace: affine
data:
  REDIS_SERVER_HOST: "redis"