apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: affine
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany  # Multi-node access
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile
  azureFile:
    secretName: azure-secret
    shareName: postgres-data
    readOnly: false

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: affine
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: azurefile

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: affine-upload-pv
  namespace: affine
spec:
 capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile
  azureFile:
    secretName: azure-secret
    shareName: affine-uploads
    readOnly: false

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: affine-upload-pvc
  namespace: affine
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: azurefile
