apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: postgres-hpa
  namespace: affine
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: postgres
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 40

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: affine-hpa
  namespace: affine
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: affine
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 40

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: affine-migration-hpa
  namespace: affine
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: affine-migration
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 40
