name: Add or Update Key/Value in AWS Secrets

on:
  workflow_dispatch:
    inputs:
      key1:
        description: 'Secret Key Name'
        type: string
        required: true
      value1:
        description: 'Secret Key Value'
        type: string
        required: true

env:
  AWS_REGION: us-east-1
  PRODUCTION_SECRET_KEY: fieldopsgpt-prod  # Secret name for production

jobs:
  aws-secrets-production:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
  
      - name: Setup jq
        uses: dcarbone/install-jq-action@v2
        with:
          version: '1.8'
          force: true
  
      - name: Load Production Secret
        id: get-secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: AWS_SECRET,${{ env.PRODUCTION_SECRET_KEY }}
  
      - name: Update Production Secret
        shell: bash
        run: |
          jq --version
          echo "INFO: Working with production environment."
          if [[ "${KEY1}" != "" ]] && [[ "${VALUE1}" != "" ]]; then
            NEW_JSON_OBJ="{ \"$KEY1\": \"$VALUE1\"}"
            MERGED=$(jq -s '.[0] * .[1]' <(echo "$AWS_SECRET") <(echo "$NEW_JSON_OBJ"))
  
            echo "INFO: Update Production Secret"
            aws secretsmanager put-secret-value \
              --secret-id "${SECRET_KEY}" \
              --secret-string "${MERGED}"
          fi
        env:
          KEY1: ${{ inputs.key1 }}
          VALUE1: ${{ inputs.value1 }}
          SECRET_KEY: ${{ env.PRODUCTION_SECRET_KEY }}
